#!/usr/bin/env python3

import sys
import ctypes as ct

if (len(sys.argv) > 2):

	if (sys.argv[1].startswith("-uint16") ):
		try:
			a = int(sys.argv[2], 16)
			print(ct.c_uint16(a).value)
		
		except:
			print("Provide a valid input, please.")

	elif (sys.argv[1].startswith("-uint32") ):
		try:
			a = int(sys.argv[2], 16)
			print(ct.c_uint32(a).value)
		
		except:
			print("Provide a valid input, please.")
	
	elif (sys.argv[1].startswith("-uint64") ):
		try:
			a = int(sys.argv[2], 16)
			print(ct.c_uint64(a).value)
		
		except:
			print("Provide a valid input, please.")

	else:
		print("You should provide an option with '-'. Is avaible: \n--> -uint16 \n--> -uint32 \n--> -uint64")



elif(len(sys.argv) == 0):
	print("You need to provide an input... Am I a magician??")

else:
	try:
		print(int(sys.argv[1], 16))
	except:
		print("Provide a valid input, please.")
    
